---
- name: ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php.ini
              regexp="date.timezone ="
              line="date.timezone = {{ timezone }}"

- name: enabling opcache cli
  lineinfile: dest=/etc/php.ini
              regexp=";?opcache.enable_cli="
              line="opcache.enable_cli=1"
